README.md
index.html
api/chat.js<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>紫微知见</title>
<style>:root{--p:#382d50;--r:#b84a45;--bg:#f6f3ec;--card:#fffdfa;--ink:#24211f;--muted:#716b64;--line:#e7e1d8}*{box-sizing:border-box}body{margin:0;background:#dedad3;color:var(--ink);font-family:-apple-system,BlinkMacSystemFont,"PingFang SC",sans-serif}.app{width:min(100%,430px);min-height:100vh;margin:auto;background:var(--bg);padding:24px 20px 80px}.top{display:flex;justify-content:space-between;align-items:center;height:50px}.brand{font:bold 23px "Songti SC",serif;letter-spacing:.12em;color:var(--p)}.tag{font-size:12px;color:var(--muted)}.card{background:var(--card);border:1px solid var(--line);border-radius:20px;padding:18px;margin-top:16px}h1{font:700 23px "Songti SC",serif;margin:0 0 5px}p{color:var(--muted);font-size:13px;line-height:1.7;margin:4px 0 14px}.profile{display:grid;grid-template-columns:1fr 1fr;gap:10px}.profile label{font-size:12px;color:var(--muted)}input,select,textarea{width:100%;border:1px solid var(--line);border-radius:11px;background:white;padding:11px;color:var(--ink);margin-top:6px;font:inherit}.wide{grid-column:1/-1}.btn{width:100%;border:0;border-radius:13px;background:var(--p);color:white;padding:14px;font-weight:700;margin-top:14px}.summary{display:none}.summary.show{display:block}.pill{display:inline-block;background:#eee9f2;color:var(--p);padding:6px 9px;border-radius:99px;font-size:11px;margin:3px}.messages{display:grid;gap:10px;margin:14px 0}.msg{padding:12px 14px;border-radius:15px;font-size:14px;line-height:1.7;white-space:pre-wrap}.assistant{background:#eee9f2}.user{background:var(--p);color:white;margin-left:34px}.row{display:flex;gap:8px}.row textarea{margin:0;min-height:48px;resize:none}.send{width:70px;border:0;border-radius:12px;background:var(--r);color:#fff;font-weight:700}.note{font-size:11px;text-align:center;color:#918a82;margin-top:14px}.loading{opacity:.55;pointer-events:none}</style></head>
<body><main class="app"><div class="top"><div class="brand">紫微知见</div><div class="tag">专业排盘 · 规则解读</div></div>
<section class="card" id="formCard"><h1>建立试用命盘</h1><p>当前版本使用虚构演示数据验证规则解读体验，正式版将接入完整排盘引擎。</p><div class="profile"><label>命盘昵称<input id="name" value="演示用户"></label><label>性别<select id="gender"><option>男</option><option>女</option></select></label><label class="wide">出生时间<input id="birth" type="datetime-local" value="2000-01-01T12:00"></label><label class="wide">出生城市<input id="city" value="示例城市"></label></div><button class="btn" id="create">生成试用命盘</button></section>
<section class="card summary" id="summary"><h1 id="chartName">命盘摘要</h1><p id="birthLine"></p><div><span class="pill">北京时间</span><span class="pill">00:00 换日</span><span class="pill">天纪四化</span><span class="pill">三方四正</span></div></section>
<section class="card summary" id="chat"><h1>规则演示解读</h1><div class="messages" id="messages"><div class="msg assistant">命盘已建立。你可以先问：我的事业优势是什么？</div></div><div class="row"><textarea id="question" placeholder="输入你想了解的问题"></textarea><button class="send" id="send">发送</button></div><div class="note">当前为免费规则演示，内容仅供传统文化研究与娱乐参考</div></section></main>
<script>const $=s=>document.querySelector(s);let history=[];let chart={};$('#create').onclick=()=>{chart={name:$('#name').value||'未命名',gender:$('#gender').value,birth:$('#birth').value,city:$('#city').value,timeRule:'北京时间；可选真太阳时；00:00换日',school:'天纪核心＋三合＋生年四化',demoFacts:{命宫:'示例：紫微、天府',官禄宫:'示例：武曲化科',财帛宫:'示例：天相',currentPeriod:'示例数据，仅用于验证AI交互'}};$('#chartName').textContent=chart.name+'的试用命盘';$('#birthLine').textContent=`${chart.birth.replace('T',' ')} · ${chart.city} · ${chart.gender}`;$('#summary').classList.add('show');$('#chat').classList.add('show');$('#question').focus()};async function send(){const q=$('#question').value.trim();if(!q)return;$('#question').value='';$('#messages').insertAdjacentHTML('beforeend',`<div class="msg user"></div>`);$('#messages').lastElementChild.textContent=q;const wait=document.createElement('div');wait.className='msg assistant';wait.textContent='正在依据命盘整理…';$('#messages').append(wait);$('#send').disabled=true;try{const r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question:q,chart,history})});const d=await r.json();if(!r.ok)throw new Error(d.error||'请求失败');wait.textContent=d.answer;history.push({role:'user',content:q},{role:'assistant',content:d.answer})}catch(e){wait.textContent='暂时无法解读：'+e.message}finally{$('#send').disabled=false;wait.scrollIntoView({behavior:'smooth'})}}$('#send').onclick=send;$('#question').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}}</script></body></html>

# 紫微知见 Vercel 免费演示版

## 部署

1. 将本目录导入 Vercel，或在目录内运行 `npx vercel`。
2. 当前版本使用本地规则生成演示解读，不需要 API Key，也不会产生模型调用费用。
3. 推送代码后，Vercel 会自动重新部署。

当前命盘和解读均为交互验证用示例结构，不能当作正式排盘结果。正式上线前需要接入并测试确定性排盘引擎。
